"""Compile reviewed memory into each coding agent's own instruction files.

Every agent reads instructions from files it already knows: AGENTS.md,
CLAUDE.md, GEMINI.md, Copilot's instruction files, Cursor, Windsurf and
Kiro rules, and Agent Skills. `lnk compile` renders the memories a person
has reviewed into those files, so they reach agents that have no MCP
connection or hooks, and keep reaching them if an agent drops its own
memory feature.

What is written, and how:

- Only reviewed, active memories. Unreviewed, archived, expired and
  quarantined (unreviewed team import) memories never are. Every memory is
  re-checked for secret-shaped values and injection-shaped instructions
  first; a flagged one is left out and reported.
- Only memories this repository should carry. Private memories are
  personal and stay out of files that get committed unless explicitly
  included. A memory fenced with `applies_when` is written only when its
  project or directory condition matches this repository; task conditions
  cannot be expressed in a static file, so those memories stay in recall.
- Always-on memories (preferences, decisions, facts, project context) go
  into one Link-owned block inside each shared file, between BEGIN/END
  markers. Everything outside the block is left byte for byte.
- Memories anchored to code (`path:line symbol @repo`) become path-scoped
  rule files in each agent's format, loaded when the agent works on those
  files. Procedure memories become Agent Skills.
- Link-owned files carry a generated-by marker. A file without it is
  never overwritten or removed; a stale Link-owned file is removed.
- Each target has a size budget. When the memories do not fit, the lowest
  priority ones (notes before facts before decisions and preferences,
  older before newer) are left out and reported - never silently cut.
- Output is deterministic: stable order, no timestamps. Compiling twice
  changes nothing, so `--check` can fail CI when the files drift from
  the store.
"""
from __future__ import annotations

import difflib
import fnmatch
import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from pathlib import Path

from .files import atomic_write_bytes
from .memory import is_active_memory, memory_quarantined, memory_visible_for_project, normalize_project, parse_applies_when
from .provenance import parse_anchor
from .security import injected_instruction_warnings, secret_value_warnings
from .staleness import repo_identity, safe_relative_path

BLOCK_BEGIN = "<!-- BEGIN LINK MEMORY: generated by `lnk compile` from reviewed Link memories; edit them in Link, not here -->"
BLOCK_END = "<!-- END LINK MEMORY -->"
OWNED_MARKER = "<!-- generated by `lnk compile` from Link memory; edit the memory in Link, not this file -->"
OWNED_PREFIX = "link-"

# Constraints first: they are what an agent most often gets wrong.
TYPE_PRIORITY = {"preference": 0, "decision": 1, "project": 2, "fact": 3, "note": 4}
ALWAYS_ON_TYPES = set(TYPE_PRIORITY)
SKILL_NAME_MAX = 64
SKILL_DESCRIPTION_MAX = 1024
DIRECTORY_GLOB_AT = 3  # anchors in this many files of one directory become dir/**


@dataclass(frozen=True)
class Target:
    """One agent file family: where it lives, its format and its budget."""

    key: str
    agent: str
    kind: str  # "block" (shared file), "rules" (one file per path-scoped memory), "always" (Link-owned always-on file), "skills"
    path: str  # file for block/always; directory for rules/skills
    budget_bytes: int | None = None
    budget_lines: int | None = None
    budget_chars: int | None = None
    budget_note: str = ""
    alternates: tuple[str, ...] = ()  # other accepted locations; an existing one is used instead
    # Paths whose presence shows the repository uses this agent. With no
    # --targets, compile writes AGENTS.md plus the agents already present,
    # instead of adding files for tools nobody here uses.
    signs: tuple[str, ...] = ()
    scoped_section: bool = False  # the agent has no path rules: list anchored memories in the block


# Budgets are the vendors' documented limits; where a vendor documents
# none, there is none here.
TARGETS: tuple[Target, ...] = (
    Target("agents-md", "Codex and other AGENTS.md readers", "block", "AGENTS.md", budget_bytes=32 * 1024,
           budget_note="Codex reads at most 32 KiB of AGENTS.md (project_doc_max_bytes) and silently drops the rest",
           signs=("",), scoped_section=True),
    Target("claude-md", "Claude Code", "block", "CLAUDE.md", budget_lines=200, alternates=(".claude/CLAUDE.md",),
           budget_note="Claude Code's guidance keeps each CLAUDE.md under 200 lines; longer files are followed less",
           signs=("CLAUDE.md", ".claude")),
    Target("gemini-md", "Gemini CLI", "block", "GEMINI.md", signs=("GEMINI.md", ".gemini"), scoped_section=True),
    Target("copilot", "GitHub Copilot", "block", ".github/copilot-instructions.md",
           signs=(".github/copilot-instructions.md", ".github/instructions")),
    Target("cursor-rules", "Cursor", "rules", ".cursor/rules", budget_lines=500,
           budget_note="Cursor's guidance keeps each rule under 500 lines", signs=(".cursor", ".cursorrules")),
    Target("claude-rules", "Claude Code", "rules", ".claude/rules", budget_lines=200,
           budget_note="Claude Code's guidance keeps each memory file under 200 lines", signs=("CLAUDE.md", ".claude")),
    Target("copilot-rules", "GitHub Copilot", "rules", ".github/instructions",
           signs=(".github/copilot-instructions.md", ".github/instructions")),
    Target("windsurf", "Windsurf", "always", ".windsurf/rules/link-memory.md", budget_chars=12_000,
           budget_note="Windsurf reads at most 12,000 characters of each rule file", signs=(".windsurf", ".windsurfrules")),
    Target("windsurf-rules", "Windsurf", "rules", ".windsurf/rules", budget_chars=12_000,
           budget_note="Windsurf reads at most 12,000 characters of each rule file", signs=(".windsurf", ".windsurfrules")),
    Target("kiro", "Kiro", "always", ".kiro/steering/link-memory.md", signs=(".kiro",)),
    Target("kiro-rules", "Kiro", "rules", ".kiro/steering", signs=(".kiro",)),
    Target("claude-skills", "Claude Code", "skills", ".claude/skills", signs=("CLAUDE.md", ".claude")),
)
TARGET_KEYS = tuple(target.key for target in TARGETS)


def detected_targets(repo: Path) -> list[str]:
    """AGENTS.md, plus every agent this repository already shows signs of using."""
    return [t.key for t in TARGETS if any(sign == "" or (repo / sign).exists() for sign in t.signs)]


@dataclass
class Plan:
    """Everything a compile would do, before anything is written."""

    repo: Path
    project: str
    files: dict[str, str] = field(default_factory=dict)      # relative path -> full new content
    removals: list[str] = field(default_factory=list)       # Link-owned files no memory produces any more
    included: dict[str, list[str]] = field(default_factory=dict)   # target key -> memory names
    dropped: list[dict[str, str]] = field(default_factory=list)    # budget cuts, per target
    excluded: list[dict[str, str]] = field(default_factory=list)   # memories not compiled, and why
    conflicts: list[dict[str, str]] = field(default_factory=list)  # files Link will not touch
    budgets: list[dict[str, object]] = field(default_factory=list)


# ── selecting memories ───────────────────────────────────────────────────

def _claim(record: Mapping[str, object]) -> str:
    text = str(record.get("tldr") or record.get("snippet") or "").strip()
    return re.sub(r"\s+", " ", text)


def _slug(value: str, limit: int = SKILL_NAME_MAX) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", str(value or "").lower()).strip("-")
    return slug[:limit].rstrip("-") or "memory"


def _sort_key(record: Mapping[str, object]) -> tuple[int, str, str]:
    # Newest first within a type; the date is part of the page, so the
    # order is the same on every machine and every run.
    date = str(record.get("updated_at") or record.get("reviewed_at") or record.get("date_captured") or "")
    inverted = "".join(chr(0x10FFFF - ord(ch)) for ch in date)
    return (TYPE_PRIORITY.get(str(record.get("memory_type") or "note"), 9), inverted, str(record.get("name") or ""))


def _applies_here(record: Mapping[str, object], project: str, repo: Path) -> tuple[bool, str]:
    """Whether a memory's applies_when fence admits this repository."""
    try:
        conditions = parse_applies_when(record.get("applies_when"))
    except ValueError:
        return False, "applies_when has invalid syntax"
    if not conditions:
        return True, ""
    for kind, argument in conditions:
        if kind == "project" and normalize_project(argument) == project:
            return True, ""
        # path: is matched against the directory a session runs in, so it
        # decides whether the memory belongs in this repository at all.
        if kind == "path" and fnmatch.fnmatch(str(repo).lower(), argument.lower()):
            return True, ""
    if all(kind == "task" for kind, _ in conditions):
        return False, "applies only to certain tasks; stays in recall"
    return False, "applies_when does not match this repository"


def select_memories(
    records: Iterable[Mapping[str, object]],
    repo: Path,
    project: str,
    *,
    include_private: bool = False,
) -> tuple[list[Mapping[str, object]], list[dict[str, str]]]:
    """(memories to compile, [{name, reason}] for every memory left out)."""
    chosen: list[Mapping[str, object]] = []
    excluded: list[dict[str, str]] = []

    def skip(record: Mapping[str, object], reason: str) -> None:
        excluded.append({"name": str(record.get("name") or ""), "title": str(record.get("title") or ""),
                         "reason": reason})

    for record in records:
        if memory_quarantined(record):
            skip(record, "unreviewed team import")
            continue
        if not is_active_memory(record):
            continue  # archived or expired: not memory any more, not worth a line
        if str(record.get("review_status") or "") != "reviewed":
            skip(record, "not reviewed")
            continue
        if not memory_visible_for_project(record, project):
            continue  # another project's memory
        if str(record.get("visibility") or "private") == "private" and not include_private:
            skip(record, "private (pass --include-private to write it into this repository's files)")
            continue
        admitted, why = _applies_here(record, project, repo)
        if not admitted:
            skip(record, why)
            continue
        text = f"{record.get('title') or ''}\n{_claim(record)}\n{record.get('body') or ''}"
        secrets = secret_value_warnings(text)
        if secrets:
            skip(record, "secret-shaped value: " + ", ".join(sorted(secrets)))
            continue
        injections = injected_instruction_warnings(text)
        if injections:
            skip(record, "injection-shaped instruction: " + ", ".join(sorted(injections)))
            continue
        if not _claim(record):
            skip(record, "no claim text")
            continue
        chosen.append(record)
    chosen.sort(key=_sort_key)
    return chosen, excluded


def _anchor_globs(record: Mapping[str, object], identity: set[str], repo: Path) -> list[str]:
    """Repository file globs for a memory's anchors in this repository."""
    anchors = record.get("anchors")
    files: list[str] = []
    for anchor in anchors if isinstance(anchors, list) else []:
        parsed = parse_anchor(str(anchor))
        if parsed is None:
            continue
        rel, _line, _symbol, root = parsed
        if not root or not any(r.startswith(root) or root.startswith(r) for r in identity):
            continue  # anchored in another repository
        if not safe_relative_path(rel) or not (repo / rel).is_file():
            continue  # gone: `lnk stale` reports it; a rule for a missing file helps no one
        if rel not in files:
            files.append(rel)
    by_dir: dict[str, list[str]] = {}
    for rel in files:
        by_dir.setdefault(rel.rsplit("/", 1)[0] if "/" in rel else "", []).append(rel)
    globs: list[str] = []
    for directory, members in sorted(by_dir.items()):
        if directory and len(members) >= DIRECTORY_GLOB_AT:
            globs.append(f"{directory}/**")
        else:
            globs.extend(sorted(members))
    return globs


# ── rendering ────────────────────────────────────────────────────────────

def _line(record: Mapping[str, object]) -> str:
    title = str(record.get("title") or record.get("name") or "").strip()
    claim = _claim(record)
    if claim.lower().rstrip(".") == title.lower().rstrip("."):
        return f"- {claim}"
    return f"- **{title}**: {claim}"


_SECTION_TITLES = (
    ("preference", "How to work"),
    ("decision", "Decisions"),
    ("project", "Project context"),
    ("fact", "Facts"),
    ("note", "Notes"),
)


def _render_list(records: list[Mapping[str, object]]) -> str:
    parts: list[str] = []
    for memory_type, heading in _SECTION_TITLES:
        lines = [_line(r) for r in records if str(r.get("memory_type") or "note") == memory_type]
        if lines:
            parts.append(f"### {heading}\n\n" + "\n".join(lines))
    return "\n\n".join(parts)


def render_block(records: list[Mapping[str, object]],
                 scoped: list[tuple[Mapping[str, object], list[str]]] | None = None) -> str:
    body = _render_list(records)
    if scoped:
        lines = [f"- `{', '.join(globs)}`: {_claim(record)}" for record, globs in scoped]
        body = (body + "\n\n" if body else "") + "### When working on these files\n\n" + "\n".join(lines)
    intro = ("Reviewed memory for this repository, compiled by Link. These are the user's standing "
             "decisions and preferences; follow them.")
    return f"{BLOCK_BEGIN}\n## Link memory\n\n{intro}\n\n{body}\n{BLOCK_END}\n"


def _frontmatter(fields: list[tuple[str, str]]) -> str:
    return "---\n" + "".join(f"{key}: {value}\n" for key, value in fields) + "---\n"


def _yaml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_always_file(target: Target, records: list[Mapping[str, object]]) -> str:
    if target.key == "windsurf":
        head = _frontmatter([("trigger", "always_on")])
    elif target.key == "kiro":
        head = _frontmatter([("inclusion", "always")])
    else:
        head = ""
    return f"{head}{OWNED_MARKER}\n\n# Link memory\n\n{_render_list(records)}\n"


def render_rule_file(target: Target, record: Mapping[str, object], globs: list[str]) -> str:
    title = str(record.get("title") or record.get("name") or "")
    description = _yaml_string(f"Link memory: {title}")
    if target.key == "cursor-rules":
        head = _frontmatter([("description", description), ("globs", ",".join(globs)), ("alwaysApply", "false")])
    elif target.key == "claude-rules":
        head = "---\npaths:\n" + "".join(f"  - {_yaml_string(g)}\n" for g in globs) + "---\n"
    elif target.key == "copilot-rules":
        head = _frontmatter([("applyTo", _yaml_string(",".join(globs)))])
    elif target.key == "windsurf-rules":
        head = _frontmatter([("trigger", "glob"), ("globs", ",".join(globs))])
    elif target.key == "kiro-rules":
        head = _frontmatter([("inclusion", "fileMatch"),
                             ("fileMatchPattern", "[" + ", ".join(_yaml_string(g) for g in globs) + "]")])
    else:
        head = ""
    return f"{head}{OWNED_MARKER}\n\n# {title}\n\n{_line(record)}\n"


def _procedure_body(record: Mapping[str, object]) -> str:
    body = str(record.get("body") or "")
    start = body.find("## Memory")
    if start >= 0:
        end = body.find("\n## ", start + 9)
        section = body[start + len("## Memory"):end if end > 0 else len(body)].strip()
    else:
        section = _claim(record)
    return section or _claim(record)


def render_skill(record: Mapping[str, object], name: str) -> str:
    title = str(record.get("title") or record.get("name") or "")
    trigger = str(record.get("trigger") or "").strip()
    description = f"{title}. Use when {trigger}." if trigger else f"{title}. {_claim(record)}"
    description = re.sub(r"\s+", " ", description).strip()[:SKILL_DESCRIPTION_MAX]
    head = _frontmatter([("name", name), ("description", _yaml_string(description))])
    return f"{head}{OWNED_MARKER}\n\n# {title}\n\n{_procedure_body(record)}\n"


# ── budgets ──────────────────────────────────────────────────────────────

def _size(text: str) -> tuple[int, int]:
    return len(text.encode("utf-8")), text.count("\n")


def _within(target: Target, text: str) -> bool:
    size, lines = _size(text)
    if target.budget_bytes is not None and size > target.budget_bytes:
        return False
    if target.budget_chars is not None and len(text) > target.budget_chars:
        return False
    return target.budget_lines is None or lines <= target.budget_lines


def _fit(target: Target, records: list[Mapping[str, object]], render) -> tuple[list[Mapping[str, object]], list[Mapping[str, object]]]:
    """Largest priority-ordered prefix of `records` whose rendering fits the budget."""
    kept = list(records)
    dropped: list[Mapping[str, object]] = []
    while kept and not _within(target, render(kept)):
        dropped.insert(0, kept.pop())  # lowest priority is last
    return kept, dropped


# ── files on disk ────────────────────────────────────────────────────────

class Unreadable(Exception):
    """A file that exists but cannot be read exactly (not UTF-8, or an I/O error)."""


def _read_strict(path: Path) -> str | None:
    """The file's text, None when it does not exist, Unreadable when it cannot be read exactly.

    A file Link cannot decode must never look missing: rewriting it from
    "nothing" would replace the person's content with Link's block.
    """
    try:
        data = path.read_bytes()
    except FileNotFoundError:
        return None
    except IsADirectoryError as exc:
        raise Unreadable("is a directory") from exc
    except OSError as exc:
        raise Unreadable(f"could not be read ({exc.strerror or exc})") from exc
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise Unreadable("is not UTF-8 text; Link will not rewrite a file it cannot read exactly") from exc


def _read(path: Path) -> str | None:
    """Lenient read for reports and diffs; planning uses _read_strict."""
    try:
        return _read_strict(path)
    except Unreadable:
        return None


def newline_of(text: str | None) -> str:
    """The line ending a file mostly uses; LF for new files."""
    if not text:
        return "\n"
    crlf = text.count("\r\n")
    return "\r\n" if crlf and crlf >= text.count("\n") - crlf else "\n"


def _with_newline(text: str, newline: str) -> str:
    return text.replace("\n", newline) if newline != "\n" else text


def splice_block(existing: str | None, block: str, newline: str = "\n") -> str:
    """Put the Link block into a shared file, keeping everything else byte for byte.

    Only Link's block, and the blank line placed before it, take `newline`;
    every existing line keeps its own ending, even in a file that mixes them.
    """
    block = _with_newline(block, newline)
    if existing is None or not existing.strip():
        return block
    begin = existing.find(BLOCK_BEGIN)
    end = existing.find(BLOCK_END)
    if begin >= 0 and end > begin:
        tail = existing[end + len(BLOCK_END):]
        if tail.startswith("\r\n"):
            tail = tail[2:]
        elif tail.startswith("\n"):
            tail = tail[1:]
        return existing[:begin] + block + tail
    if begin >= 0 or end >= 0:
        raise ValueError("has a Link memory marker without its partner; fix or remove the marker by hand")
    if existing.endswith(("\n\n", "\r\n\r\n", "\n\r\n")):
        separator = ""
    elif existing.endswith("\n"):
        separator = newline
    else:
        separator = newline + newline
    return existing + separator + block


def remove_block(existing: str, newline: str = "\n") -> str:
    begin = existing.find(BLOCK_BEGIN)
    end = existing.find(BLOCK_END)
    if begin < 0 or end < begin:
        return existing
    tail = existing[end + len(BLOCK_END):].lstrip("\r\n")
    head = existing[:begin].rstrip("\r\n")
    if not head:
        return tail
    return head + (newline * 2 + tail if tail else newline)


def _owned_file_refusal(repo: Path, rel: str, taken: str = "exists and was not written by Link; left alone") -> str | None:
    """Why Link may not write its own file at `rel`, or None when it may.

    Symlinked, unreadable and hand-written files are all left alone.
    """
    refusal = _guard_path(repo, rel)
    if refusal:
        return refusal
    try:
        existing = _read_strict(repo / rel)
    except Unreadable as exc:
        return str(exc)
    if existing is not None and not _owned(existing):
        return taken
    return None


def _owned(text: str | None) -> bool:
    return text is not None and OWNED_MARKER in text


def _is_link_block_only(text: str) -> bool:
    return text.strip().startswith(BLOCK_BEGIN) and text.strip().endswith(BLOCK_END)


def _guard_path(repo: Path, rel: str) -> str | None:
    """Why Link must not write `rel`, or None when it may."""
    target = repo / rel
    probe = target
    while probe != repo and probe != probe.parent:
        if probe.is_symlink():
            return "is (or is inside) a symlink; Link does not write through links"
        probe = probe.parent
    return None


# ── planning ─────────────────────────────────────────────────────────────

def plan_compile(
    records: Iterable[Mapping[str, object]],
    repo: Path,
    *,
    project: str | None = None,
    targets: Iterable[str] | None = None,
    include_private: bool = False,
) -> Plan:
    """Work out every file compile would write or remove. Writes nothing."""
    repo = Path(repo).expanduser().resolve()
    project_name = normalize_project(project or repo.name)
    if targets is None:
        targets = detected_targets(repo)
    elif "all" in set(targets):
        targets = list(TARGET_KEYS)
    wanted = [t for t in TARGETS if t.key in set(targets)]
    plan = Plan(repo=repo, project=project_name)
    memories, plan.excluded = select_memories(records, repo, project_name, include_private=include_private)
    identity = repo_identity(repo)
    procedures = [m for m in memories if str(m.get("memory_type") or "") == "procedure"]
    anchored = {str(m.get("name")): _anchor_globs(m, identity, repo) for m in memories
                if str(m.get("memory_type") or "") != "procedure"}
    always_on = [m for m in memories if str(m.get("memory_type") or "") in ALWAYS_ON_TYPES
                 and not anchored.get(str(m.get("name")))]
    path_scoped = [m for m in memories if anchored.get(str(m.get("name")))]

    def _block_for(chosen: list[Mapping[str, object]]) -> str:
        scoped_names = {str(m.get("name")) for m in path_scoped}
        return render_block([m for m in chosen if str(m.get("name")) not in scoped_names],
                            [(m, anchored[str(m.get("name"))]) for m in chosen if str(m.get("name")) in scoped_names])

    def note_budget(target: Target, rel: str, text: str) -> None:
        size, lines = _size(text)
        plan.budgets.append({"target": target.key, "path": rel, "bytes": size, "chars": len(text), "lines": lines,
                             "budget_bytes": target.budget_bytes, "budget_chars": target.budget_chars,
                             "budget_lines": target.budget_lines})

    def drop(target: Target, rel: str, cut: list[Mapping[str, object]]) -> None:
        for record in cut:
            plan.dropped.append({"target": target.key, "path": rel, "name": str(record.get("name") or ""),
                                 "title": str(record.get("title") or ""),
                                 "reason": target.budget_note or "over this file's size budget"})

    for target in wanted:
        if target.kind == "block":
            location = target.path
            if not (repo / location).exists():
                location = next((alt for alt in target.alternates if (repo / alt).is_file()), location)
            refusal = _guard_path(repo, location)
            if refusal:
                plan.conflicts.append({"target": target.key, "path": location, "reason": refusal})
                continue
            try:
                existing = _read_strict(repo / location)
            except Unreadable as exc:
                plan.conflicts.append({"target": target.key, "path": location, "reason": str(exc)})
                continue
            newline = newline_of(existing)
            if existing and (BLOCK_BEGIN in existing or BLOCK_END in existing):
                try:
                    splice_block(existing, "")  # a lone marker is the user's to fix, not ours to guess
                except ValueError as exc:
                    plan.conflicts.append({"target": target.key, "path": location, "reason": str(exc)})
                    continue
            outside = remove_block(existing, newline) if existing else ""

            def clear_block(existing: str | None = existing, location: str = location) -> None:
                """No memories for this file any more: take Link's block out."""
                if not existing or BLOCK_BEGIN not in existing:
                    return
                try:
                    splice_block(existing, "")  # validates the markers
                except ValueError as exc:
                    plan.conflicts.append({"target": target.key, "path": location, "reason": str(exc)})
                    return
                if remove_block(existing, newline).strip():
                    plan.files[location] = remove_block(existing, newline)
                else:
                    plan.removals.append(location)  # the file only ever held Link's block

            # Agents without path rules still get anchored memories, listed
            # with their files; they are the first to go when space runs out.
            entries = always_on + (path_scoped if target.scoped_section else [])
            if not entries:
                clear_block()
                continue

            def whole(chosen: list[Mapping[str, object]], outside: str = outside, newline: str = newline) -> str:
                return splice_block(outside or None, _block_for(chosen), newline)
            kept, cut = _fit(target, entries, whole)
            if cut and not _within(target, outside or ""):
                own = _size(outside)
                note = f"{target.budget_note}; the file's own content already uses {own[0]} bytes / {own[1]} lines"
                for record in cut:
                    plan.dropped.append({"target": target.key, "path": location, "name": str(record.get("name") or ""),
                                         "title": str(record.get("title") or ""), "reason": note})
            else:
                drop(target, location, cut)
            if not kept:
                clear_block()
                continue
            try:
                content = splice_block(existing, _block_for(kept), newline)
            except ValueError as exc:
                plan.conflicts.append({"target": target.key, "path": location, "reason": str(exc)})
                continue
            plan.files[location] = content
            plan.included[target.key] = [str(r.get("name")) for r in kept]
            note_budget(target, location, content)
        elif target.kind == "always":
            refusal = _owned_file_refusal(repo, target.path)
            if refusal:
                plan.conflicts.append({"target": target.key, "path": target.path, "reason": refusal})
                continue
            kept, cut = _fit(target, always_on, lambda chosen, t=target: render_always_file(t, chosen))
            drop(target, target.path, cut)
            if kept:
                content = render_always_file(target, kept)
                plan.files[target.path] = content
                plan.included[target.key] = [str(r.get("name")) for r in kept]
                note_budget(target, target.path, content)
        elif target.kind == "rules":
            suffix = {"cursor-rules": ".mdc", "copilot-rules": ".instructions.md"}.get(target.key, ".md")
            names: list[str] = []
            for record in path_scoped:
                rel = f"{target.path}/{OWNED_PREFIX}{_slug(str(record.get('name')))}{suffix}"
                refusal = _owned_file_refusal(repo, rel)
                if refusal:
                    plan.conflicts.append({"target": target.key, "path": rel, "reason": refusal})
                    continue
                content = render_rule_file(target, record, anchored[str(record.get("name"))])
                if not _within(target, content):
                    drop(target, rel, [record])
                    continue
                plan.files[rel] = content
                names.append(str(record.get("name")))
                note_budget(target, rel, content)
            if names:
                plan.included[target.key] = names
        elif target.kind == "skills":
            names = []
            for record in procedures:
                name = _slug(str(record.get("name")))
                rel = f"{target.path}/{name}/SKILL.md"
                refusal = _owned_file_refusal(
                    repo, rel, "a skill with this name exists and was not written by Link; left alone")
                if refusal:
                    plan.conflicts.append({"target": target.key, "path": rel, "reason": refusal})
                    continue
                plan.files[rel] = render_skill(record, name)
                names.append(str(record.get("name")))
            if names:
                plan.included[target.key] = names

    # Link-owned files that no memory produces any more. The always-on files
    # of Kiro and Windsurf share a directory with their path rules, so they
    # are never treated as stale rules.
    always_paths = {t.path for t in TARGETS if t.kind == "always"}
    for target in wanted:
        if target.kind == "rules":
            directory = repo / target.path
            pattern = f"{OWNED_PREFIX}*"
            for path in sorted(directory.glob(pattern)) if directory.is_dir() else []:
                rel = path.relative_to(repo).as_posix()
                if rel in always_paths:
                    continue
                if rel not in plan.files and path.is_file() and not path.is_symlink() and _owned(_read(path)):
                    plan.removals.append(rel)
        elif target.kind == "always":
            path = repo / target.path
            if target.path not in plan.files and path.is_file() and not path.is_symlink() and _owned(_read(path)):
                plan.removals.append(target.path)
        elif target.kind == "skills":
            directory = repo / target.path
            for skill in sorted(directory.glob("*/SKILL.md")) if directory.is_dir() else []:
                rel = skill.relative_to(repo).as_posix()
                if rel not in plan.files and not skill.is_symlink() and _owned(_read(skill)):
                    plan.removals.append(rel)
    return plan


def plan_changes(plan: Plan) -> list[dict[str, str]]:
    """Files whose content on disk differs from the plan: [{path, action}]."""
    changes: list[dict[str, str]] = []
    for rel, content in sorted(plan.files.items()):
        current = _read(plan.repo / rel)
        if current != content:
            changes.append({"path": rel, "action": "create" if current is None else "update"})
    for rel in sorted(plan.removals):
        changes.append({"path": rel, "action": "remove"})
    return changes


def plan_diff(plan: Plan) -> str:
    chunks: list[str] = []
    for change in plan_changes(plan):
        rel = change["path"]
        before = _read(plan.repo / rel) or ""
        after = "" if change["action"] == "remove" else plan.files[rel]
        chunks.extend(difflib.unified_diff(before.splitlines(keepends=True), after.splitlines(keepends=True),
                                           fromfile=f"a/{rel}", tofile=f"b/{rel}"))
    return "".join(chunks)


def apply_plan(plan: Plan) -> list[dict[str, str]]:
    """Write the plan. Only files in the plan are touched; returns what changed."""
    changes = plan_changes(plan)
    for change in changes:
        rel = change["path"]
        path = plan.repo / rel
        if change["action"] == "remove":
            path.unlink()
            parent = path.parent
            if parent.name != Path(rel).parts[0] and parent != plan.repo and not any(parent.iterdir()):
                parent.rmdir()  # an emptied skill directory
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_bytes(path, plan.files[rel].encode("utf-8"))
    return changes


def plan_summary(plan: Plan, changes: list[dict[str, str]]) -> dict[str, object]:
    return {
        "repo": str(plan.repo),
        "project": plan.project,
        "changes": changes,
        "included": plan.included,
        "dropped": plan.dropped,
        "excluded": plan.excluded,
        "conflicts": plan.conflicts,
        "budgets": plan.budgets,
    }
